### ISSUE TITLE
Crash when starting on heroku

### ISSUE THREAD

**Issue by Mov1s** [plexinc/webhooks-slack#3]
I can't get the app to start when using the 'Deploy To Heroku' button in the README. After configuring all of the params and starting the app I get the following in the logs:
```
2017-02-23T18:07:21.221494+00:00 heroku[web.1]: Starting process with command `npm start`
2017-02-23T18:07:25.124147+00:00 app[web.1]: 
2017-02-23T18:07:25.124174+00:00 app[web.1]: > plex-notifications@0.0.1 start /app
2017-02-23T18:07:25.124175+00:00 app[web.1]: > node index.js
2017-02-23T18:07:25.124176+00:00 app[web.1]: 
2017-02-23T18:07:26.251495+00:00 app[web.1]: dns.js:112
2017-02-23T18:07:26.251507+00:00 app[web.1]:     throw new TypeError('Invalid arguments: ' +
2017-02-23T18:07:26.251508+00:00 app[web.1]:     ^
2017-02-23T18:07:26.251509+00:00 app[web.1]: 
2017-02-23T18:07:26.251510+00:00 app[web.1]: TypeError: Invalid arguments: hostname must be a string or falsey
2017-02-23T18:07:26.251511+00:00 app[web.1]:     at lookup (dns.js:112:11)
2017-02-23T18:07:26.251511+00:00 app[web.1]:     at lookupAndConnect (net.js:991:3)
2017-02-23T18:07:26.251512+00:00 app[web.1]:     at Socket.connect (net.js:936:5)
2017-02-23T18:07:26.251513+00:00 app[web.1]:     at Object.exports.connect.exports.createConnection (net.js:74:35)
2017-02-23T18:07:26.251513+00:00 app[web.1]:     at RedisClient.create_stream (/app/node_modules/redis/index.js:251:31)
2017-02-23T18:07:26.251514+00:00 app[web.1]:     at new RedisClient (/app/node_modules/redis/index.js:159:10)
2017-02-23T18:07:26.251515+00:00 app[web.1]:     at Object.exports.createClient (/app/node_modules/redis/index.js:1084:12)
2017-02-23T18:07:26.251515+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:16:25)
2017-02-23T18:07:26.251516+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-23T18:07:26.251517+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-02-23T18:07:26.278338+00:00 app[web.1]: 
2017-02-23T18:07:26.294877+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-02-23T18:07:26.295222+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-02-23T18:07:26.295459+00:00 app[web.1]: npm ERR! node v6.10.0
2017-02-23T18:07:26.295697+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-02-23T18:07:26.295930+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-02-23T18:07:26.296128+00:00 app[web.1]: npm ERR! plex-notifications@0.0.1 start: `node index.js`
2017-02-23T18:07:26.296299+00:00 app[web.1]: npm ERR! Exit status 1
2017-02-23T18:07:26.296499+00:00 app[web.1]: npm ERR! 
2017-02-23T18:07:26.301192+00:00 app[web.1]: npm ERR! Failed at the plex-notifications@0.0.1 start script 'node index.js'.
2017-02-23T18:07:26.301372+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-02-23T18:07:26.301527+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the plex-notifications package,
2017-02-23T18:07:26.301684+00:00 app[web.1]: npm ERR! not with npm itself.
2017-02-23T18:07:26.301862+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-02-23T18:07:26.302035+00:00 app[web.1]: npm ERR!     node index.js
2017-02-23T18:07:26.302182+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-02-23T18:07:26.302322+00:00 app[web.1]: npm ERR!     npm bugs plex-notifications
2017-02-23T18:07:26.302463+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-02-23T18:07:26.302604+00:00 app[web.1]: npm ERR!     npm owner ls plex-notifications
2017-02-23T18:07:26.302753+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-02-23T18:07:26.311493+00:00 app[web.1]: 
2017-02-23T18:07:26.311783+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-02-23T18:07:26.311929+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-02-23T18:07:26.463845+00:00 heroku[web.1]: Process exited with status 1
2017-02-23T18:07:26.483413+00:00 heroku[web.1]: State changed from starting to crashed
```

Am I configuring something wrong? My params look like this:
```
SLACK_URL="https://hooks.slack.com/services/..."
SLACK_CHANNEL="#general"
APP_URL="https://myapp.herokuapp.com"
```

**Comment by elan** [comment]
@BigAlUK ~ Any idea?

**Comment by BigAlUK** [comment]
Sorry! Totally my fault, missed the Redis config var update in `index.js` PR raised: [https://github.com/plexinc/webhooks-slack/pull/4](https://github.com/plexinc/webhooks-slack/pull/4)

**Comment by BigAlUK** [comment]
Went through the build process on Heroku this morning.  It built fine and could see `200`s in the logs with requests from Plex Webhooks to app.  Hopefully this sorts it. Sorry again for the issue.
