### ISSUE TITLE
heroku build failed

### ISSUE THREAD

**Issue by willruss1** [plexinc/webhooks-slack#5]
deploy to heroku fails, admitted newb with heroku so not sure if I'm doing something wrong. The instructions seem pretty straightforward, though, so I kinda doubt I am.

Build log below:

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x via semver.io...
       Downloading and installing node 6.10.2...
       Using default npm version: 3.10.10
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (package.json)
       
       > lwip@0.0.9 install /tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/node_modules/lwip
       > node-gyp rebuild
       
       make: Entering directory `/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/node_modules/lwip/build'
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
       ../src/decoder/buffer_worker.cpp: In constructor ‘DecodeBufferWorker::DecodeBufferWorker(Nan::Callback*, v8::Local<v8::Object>&, buf_dec_f_t)’:
       ../src/decoder/buffer_worker.cpp:8:58: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       _height(0), _channels(0), _trans(false), _metadata("") {
       ^
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
       CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jcomapi.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapimin.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapistd.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatadst.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatasrc.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcoefct.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcolor.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jddctmgr.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdhuff.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdinput.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmainct.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmarker.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmaster.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdpostct.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdsample.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jerror.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctflt.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctfst.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctint.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctflt.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctfst.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctint.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jutils.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemmgr.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdarith.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmerge.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jaricom.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant1.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant2.o
       CC(target) Release/obj.target/lwip_decoder/src/lib/png/png.o
       In file included from ../src/lib/png/png.c:14:0:
       ../src/lib/png/pngpriv.h:805:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
       #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM     ^
       make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
       make: Leaving directory `/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/node_modules/lwip/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! System Linux 3.13.0-112-generic
       gyp ERR! command "/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.heroku/node/bin/node" "/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/node_modules/lwip
       gyp ERR! node -v v6.10.2
       gyp ERR! node-gyp -v v3.4.0
       gyp ERR! not ok
       plex-notifications@0.0.1 /tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a
       ├─┬ express@4.15.2
       │ ├─┬ accepts@1.3.3
       │ │ ├─┬ mime-types@2.1.15
       │ │ │ └── mime-db@1.27.0
       │ │ └── negotiator@0.6.1
       │ ├── array-flatten@1.1.1
       │ ├── content-disposition@0.5.2
       │ ├── content-type@1.0.2
       │ ├── cookie@0.3.1
       │ ├── cookie-signature@1.0.6
       │ ├─┬ debug@2.6.1
       │ │ └── ms@0.7.2
       │ ├── depd@1.1.0
       │ ├── encodeurl@1.0.1
       │ ├── escape-html@1.0.3
       │ ├── etag@1.8.0
       │ ├─┬ finalhandler@1.0.1
       │ │ ├── debug@2.6.3
       │ │ └── unpipe@1.0.0
       │ ├── fresh@0.5.0
       │ ├── merge-descriptors@1.0.1
       │ ├── methods@1.1.2
       │ ├─┬ on-finished@2.3.0
       │ │ └── ee-first@1.1.1
       │ ├── parseurl@1.3.1
       │ ├── path-to-regexp@0.1.7
       │ ├─┬ proxy-addr@1.1.4
       │ │ ├── forwarded@0.1.0
       │ │ └── ipaddr.js@1.3.0
       │ ├── qs@6.4.0
       │ ├── range-parser@1.2.0
       │ ├─┬ send@0.15.1
       │ │ ├── destroy@1.0.4
       │ │ ├── http-errors@1.6.1
       │ │ └── mime@1.3.4
       │ ├── serve-static@1.12.1
       │ ├── setprototypeof@1.0.3
       │ ├── statuses@1.3.1
       │ ├─┬ type-is@1.6.15
       │ │ └── media-typer@0.3.0
       │ ├── utils-merge@1.0.0
       │ └── vary@1.1.1
       ├─┬ multer@1.3.0
       │ ├── append-field@0.1.0
       │ ├─┬ busboy@0.2.14
       │ │ ├─┬ dicer@0.2.5
       │ │ │ └── streamsearch@0.1.2
       │ │ └─┬ readable-stream@1.1.14
       │ │   ├── core-util-is@1.0.2
       │ │   ├── isarray@0.0.1
       │ │   └── string_decoder@0.10.31
       │ ├─┬ concat-stream@1.6.0
       │ │ ├── inherits@2.0.3
       │ │ ├─┬ readable-stream@2.2.6
       │ │ │ ├── buffer-shims@1.0.0
       │ │ │ ├── isarray@1.0.0
       │ │ │ ├── process-nextick-args@1.0.7
       │ │ │ └── util-deprecate@1.0.2
       │ │ └── typedarray@0.0.6
       │ ├─┬ mkdirp@0.5.1
       │ │ └── minimist@0.0.8
       │ ├── object-assign@3.0.0
       │ └── xtend@4.0.1
       ├─┬ node-freegeoip@0.0.1
       │ └─┬ request@2.81.0
       │   ├── aws-sign2@0.6.0
       │   ├── aws4@1.6.0
       │   ├── caseless@0.12.0
       │   ├─┬ combined-stream@1.0.5
       │   │ └── delayed-stream@1.0.0
       │   ├── extend@3.0.0
       │   ├── forever-agent@0.6.1
       │   ├─┬ form-data@2.1.2
       │   │ └── asynckit@0.4.0
       │   ├─┬ har-validator@4.2.1
       │   │ ├─┬ ajv@4.11.5
       │   │ │ ├── co@4.6.0
       │   │ │ └─┬ json-stable-stringify@1.0.1
       │   │ │   └── jsonify@0.0.0
       │   │ └── har-schema@1.0.5
       │   ├─┬ hawk@3.1.3
       │   │ ├── boom@2.10.1
       │   │ ├── cryptiles@2.0.5
       │   │ ├── hoek@2.16.3
       │   │ └── sntp@1.0.9
       │   ├─┬ http-signature@1.1.1
       │   │ ├── assert-plus@0.2.0
       │   │ ├─┬ jsprim@1.4.0
       │   │ │ ├── assert-plus@1.0.0
       │   │ │ ├── extsprintf@1.0.2
       │   │ │ ├── json-schema@0.2.3
       │   │ │ └── verror@1.3.6
       │   │ └─┬ sshpk@1.11.0
       │   │   ├── asn1@0.2.3
       │   │   ├── assert-plus@1.0.0
       │   │   ├── bcrypt-pbkdf@1.0.1
       │   │   ├─┬ dashdash@1.14.1
       │   │   │ └── assert-plus@1.0.0
       │   │   ├── ecc-jsbn@0.1.1
       │   │   ├─┬ getpass@0.1.6
       │   │   │ └── assert-plus@1.0.0
       │   │   ├── jodid25519@1.0.2
       │   │   ├── jsbn@0.1.1
       │   │   └── tweetnacl@0.14.5
       │   ├── is-typedarray@1.0.0
       │   ├── isstream@0.1.2
       │   ├── json-stringify-safe@5.0.1
       │   ├── oauth-sign@0.8.2
       │   ├── performance-now@0.2.0
       │   ├── safe-buffer@5.0.1
       │   ├── stringstream@0.0.5
       │   ├─┬ tough-cookie@2.3.2
       │   │ └── punycode@1.4.1
       │   ├── tunnel-agent@0.6.0
       │   └── uuid@3.0.1
       ├─┬ redis@2.7.1
       │ ├── double-ended-queue@2.1.0-0
       │ ├── redis-commands@1.3.1
       │ └── redis-parser@2.6.0
       ├─┬ sha1@1.1.1
       │ ├── charenc@0.0.2
       │ └── crypt@0.0.2
       └─┬ slack-node@0.1.8
       └─┬ requestretry@1.12.0
       ├── lodash@4.17.4
       └── when@3.7.8
       
       npm ERR! Linux 3.13.0-112-generic
       npm ERR! argv "/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.heroku/node/bin/node" "/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/.npmrc"
       npm ERR! node v6.10.2
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       
       npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the lwip package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp rebuild
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs lwip
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls lwip
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_4d001b81511928402d4df9ba2e104e1e/plexinc-webhooks-slack-328f72a/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by elan** [comment]
Hmm, that's a weird one, haven't seen it before. Some version mismatch is likely, just not sure what.

**Comment by willruss1** [comment]
Not sure what exactly changed; but it does build successfully now on heroku. 

Still not getting any posts to the channel for playback events; but it's a step in the right direction.
